name: BitzTest
main: com.rayzr522.bitztest.BitzTest
version: 1.0
description: "Just a small test plugin for BitzAPI"
author: Rayzr522
depend: [BitzAPI]
commands:
  nameitem:
    description: "Name item"
    usage: "/nameitem"
  playerInfo:
    description: "STuff"
    usage: "/playerInfo"
  debug:
    description: "Debugs LoreData"
    usage: "/debug [item]"
  watch:
    description: "Watch a player"
    usage: "/watch <player>"
  rp:
    description: "Get the resource pack"
    usage: "/rp"